export default {
	DESCRIPTION: 'Living assistant',
	REGISTER: 'Register',
	LOGIN: 'Login',
	EMAIL: 'Email',
	PASSWORD: 'Password',
	CONFIRM_PASSWORD: 'Confirm password',
	LOGO: 'Logo',
	PASSWORD_MISMATCH: 'Password mismatch',
	EMAIL_EXISTED: 'Email existed',
	EMAIL_REQUIRED: 'Email is required',
	INVALID_EMAIL: 'Invalid email',
	PASSWORD_REQUIRED: 'Password is required',
	CONFIRM_PASSWORD_REQUIRED: 'Confirm password is required',
	INVALID_PASSWORD: 'Password contains at least 6 characters',
	SHOW_PASSWORD: 'Show password',
	DISHES: 'Dishes',
	LOGOUT: 'Logout',
	INVALID_EMAIL_OR_PASSWORD: 'Invalid email or password'
};
