name: cd

on:
  push:
    branches: [main]

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: echo "${{ secrets.ENV }}" > .env
      - run: npm run build
      - run: cp -r package.json package-lock.json prisma/ build/
      - run: cd build && npm ci --omit=dev --ignore-scripts --platform=linux --arch=x64 && npx prisma generate
      - uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: build/
          ARGS: -avzr --delete
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/${{ secrets.REMOTE_USER }}/${{ github.event.repository.name }}
